name: csun23
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sliver_tools: ^0.2.9
  intl: ^0.18.0
  collection: ^1.17.0
  flutter_riverpod: ^2.3.1
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  icon_decoration: ^1.0.1
  flutter_launcher_icons: ^0.12.0
  accessible_text_view: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"
  min_sdk_android: 21
